Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -12,47 +12,47 @@ on:
       - main
 
 jobs:
-  generate-tags:
-      runs-on: ubuntu-latest
-      outputs:
-        tag: ${{ steps.anothr-Nick.outputs.tag }}
-        new_tag: ${{ steps.anothr-Nick.outputs.new_tag }}
-      steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: '0'
-      - name: Generate tags
-        id: anothr-Nick
-        uses: anothrNick/github-tag-action@1.36.0
-        env:
-          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
-          WITH_V: true
-          DRY_RUN: True
+#   generate-tags:
+#       runs-on: ubuntu-latest
+#       outputs:
+#         tag: ${{ steps.anothr-Nick.outputs.tag }}
+#         new_tag: ${{ steps.anothr-Nick.outputs.new_tag }}
+#       steps:
+#       - uses: actions/checkout@v3
+#         with:
+#           fetch-depth: '0'
+#       - name: Generate tags
+#         id: anothr-Nick
+#         uses: anothrNick/github-tag-action@1.36.0
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
+#           WITH_V: true
+#           DRY_RUN: True
   
-  build-and-publish:  
-    needs: generate-tags
-    if: needs.generate-tags.outputs.new_tag!=needs.generate-tags.outputs.tag # To manage pipeline from failing if "#none" is added in commit message
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: '0'
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        java-version: '11'
-        distribution: 'temurin'
-        server-id: github 
-        settings-path: ${{ github.workspace }} # location for the settings.xml file
+#   build-and-publish:  
+#     needs: generate-tags
+#     if: needs.generate-tags.outputs.new_tag!=needs.generate-tags.outputs.tag # To manage pipeline from failing if "#none" is added in commit message
+#     runs-on: ubuntu-latest
+#     steps:
+#     - uses: actions/checkout@v3
+#       with:
+#         fetch-depth: '0'
+#     - name: Set up JDK 11
+#       uses: actions/setup-java@v3
+#       with:
+#         java-version: '11'
+#         distribution: 'temurin'
+#         server-id: github 
+#         settings-path: ${{ github.workspace }} # location for the settings.xml file
       
-    - name: Build with Maven
-      run: mvn -B package --file pom.xml       
+#     - name: Build with Maven
+#       run: mvn -B package --file pom.xml       
         
-    - name: Update version
-      run: mvn versions:set -DnewVersion=${{ needs.generate-tags.outputs.tag }}
+#     - name: Update version
+#       run: mvn versions:set -DnewVersion=${{ needs.generate-tags.outputs.tag }}
 
-    - name: Commit Version
-      run: mvn versions:commit 
+#     - name: Commit Version
+#       run: mvn versions:commit 
         
 #     - name: publish version
 #       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
